apiVersion: v1
kind: PersistentVolume
metadata:
  name: ecp-maven-s3-pv
spec:
  capacity:
    storage: 100Gi  # Ignored by Mountpoint, required by K8s
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  mountOptions:
    - allow-delete
    - allow-overwrite
    - allow-other
    - "metadata-ttl 300"
    - "read-part-size 5242880"
    - "max-threads 16"
    - uid=1000
    - gid=1000
    - "region ap-south-1"
  csi:
    driver: s3.csi.aws.com
    volumeHandle: ecp-maven-s3-pv
    volumeAttributes:
      bucketName: 864899852480-ecp-lab-elastic-cicd-maven-m2
      # Cache to node's EBS root volume (emptyDir without Memory medium)
      cache: emptyDir
      cacheEmptyDirSizeLimit: 8Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ecp-maven-s3-pvc
  #namespace: elastic-cicd
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: ecp-maven-s3-pv
  resources:
    requests:
      storage: 100Gi
